{{- if .Values.tomcatUsers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tomcat-helm-chart.fullname" . }}-credentials
  labels:
    {{- include "tomcat-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  tomcat-username: {{ .Values.tomcatUsers.username | b64enc | quote }}
  tomcat-password: {{ .Values.tomcatUsers.password | b64enc | quote }}
  {{- if .Values.database }}
  db-username: {{ .Values.database.username | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-url: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
{{- end }}